import Product from "./models/Product.js";
import { connectDB } from "./config/db.js";
import mongoose from "mongoose";

const seedDB = async () => {
    try {
        await connectDB();
        console.log("Clearing existing products...");
        await Product.deleteMany({});
        console.log("Cleared existing products");

        const products: any = [
            {
                name: "Aashirvaad Whole Wheat Atta",
                description: "100% MP Sharbati wheat, soft rotis that stay soft longer",
                price: 250,
                originalPrice: 280,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ooitbkcjcky0gkjmkatb.png",
                category: "pantry-staples",
                unit: "5kg",
                stock: 150,
                isOrganic: false,
                rating: 4.8,
                reviewCount: 345,
                hasVariants: true,
                variants: [
                    { sku: "AASH-ATTA-1KG", unit: "1kg", price: 55, originalPrice: 60, stock: 100 },
                    { sku: "AASH-ATTA-5KG", unit: "5kg", price: 250, originalPrice: 280, stock: 150 }
                ]
            },
            {
                name: "India Gate Basmati Rice 1kg",
                description: "Long grain aromatic basmati rice for daily use",
                price: 135,
                originalPrice: 150,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/evuovl2nlwdjukosfz23.png",
                category: "pantry-staples",
                unit: "1kg",
                stock: 120,
                isOrganic: false,
                rating: 4.7,
                reviewCount: 230,
            },
            {
                name: "Tata Salt 1kg",
                description: "Vacuum evaporated iodised salt",
                price: 25,
                originalPrice: 28,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cxrrgnf12xuhkr4dyhi2.png",
                category: "pantry-staples",
                unit: "1kg",
                stock: 500,
                isOrganic: false,
                rating: 4.9,
                reviewCount: 512,
            },
            {
                name: "Toor Dal 1kg",
                description: "Premium unpolished toor dal, rich in protein",
                price: 165,
                originalPrice: 180,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/spb5sgy8g24rned9nwog.png",
                category: "pantry-staples",
                unit: "1kg",
                stock: 200,
                isOrganic: true,
                rating: 4.6,
                reviewCount: 156,
            },
            {
                name: "Amul Butter 500g",
                description: "Pasteurised butter, utterly butterfly delicious",
                price: 285,
                originalPrice: 295,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/gek3mmiig3lixlkpxks8.png",
                category: "dairy-eggs",
                unit: "500g",
                stock: 80,
                isOrganic: false,
                rating: 4.9,
                reviewCount: 410,
            },
            {
                name: "Amul Taaza Milk",
                description: "Toned milk, homogenized, packed in carton",
                price: 68,
                originalPrice: 70,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/ooamzy497lhsj2gjuwby.png",
                category: "dairy-eggs",
                unit: "1L",
                stock: 100,
                isOrganic: false,
                rating: 4.8,
                reviewCount: 890,
                hasVariants: true,
                variants: [
                    { sku: "AMUL-TAA-500ML", unit: "500ml", price: 35, originalPrice: 38, stock: 50 },
                    { sku: "AMUL-TAA-1L", unit: "1L", price: 68, originalPrice: 70, stock: 100 }
                ]
            },
            {
                name: "Fresh Paneer 200g",
                description: "Soft and fresh malai paneer, rich in protein",
                price: 85,
                originalPrice: 95,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vihqr6wquv57byurvz46.png",
                category: "dairy-eggs",
                unit: "200g",
                stock: 45,
                isOrganic: false,
                rating: 4.6,
                reviewCount: 220,
            },
            {
                name: "Haldiram's Bhujia Sev 400g",
                description: "Crispy and spicy gram flour noodles",
                price: 110,
                originalPrice: 120,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vnzb2qbwtpab5gnqvx0f.png",
                category: "snacks",
                unit: "400g",
                stock: 300,
                isOrganic: false,
                rating: 4.8,
                reviewCount: 420,
            },
            {
                name: "Maggi 2-Minute Noodles 280g",
                description: "Masala noodles pack of 4",
                price: 55,
                originalPrice: 60,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/dsep7owmwvfrukzbslqo.png",
                category: "snacks",
                unit: "280g",
                stock: 400,
                isOrganic: false,
                rating: 4.9,
                reviewCount: 850,
            },
            {
                name: "Britannia Good Day Cashew 600g",
                description: "Rich cashew cookies",
                price: 120,
                originalPrice: 140,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vy1xa7zovcu22smzapzv.png",
                category: "bakery",
                unit: "600g",
                stock: 120,
                isOrganic: false,
                rating: 4.7,
                reviewCount: 330,
            },
            {
                name: "MDH Garam Masala 100g",
                description: "Aromatic blend of Indian spices",
                price: 85,
                originalPrice: 90,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cxrrgnf12xuhkr4dyhi2.png",
                category: "pantry-staples",
                unit: "100g",
                stock: 150,
                isOrganic: false,
                rating: 4.8,
                reviewCount: 190,
            },
            {
                name: "Everest Turmeric Powder 100g",
                description: "Pure haldi powder, rich in curcumin",
                price: 35,
                originalPrice: 40,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/spb5sgy8g24rned9nwog.png",
                category: "pantry-staples",
                unit: "100g",
                stock: 160,
                isOrganic: true,
                rating: 4.7,
                reviewCount: 180,
            },
            {
                name: "Brooke Bond Red Label Tea 500g",
                description: "Strong tea with great taste and aroma",
                price: 245,
                originalPrice: 260,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/cxrrgnf12xuhkr4dyhi2.png",
                category: "beverages",
                unit: "500g",
                stock: 130,
                isOrganic: false,
                rating: 4.8,
                reviewCount: 450,
            },
            {
                name: "Nescafe Classic Coffee 50g",
                description: "100% pure instant coffee",
                price: 170,
                originalPrice: 185,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vnzb2qbwtpab5gnqvx0f.png",
                category: "beverages",
                unit: "50g",
                stock: 90,
                isOrganic: false,
                rating: 4.8,
                reviewCount: 520,
            },
            {
                name: "Farm Fresh Tomato 1 kg",
                description: "Juicy and ripe red tomatoes",
                price: 45,
                originalPrice: 55,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/kdbfytxisrjymgy0ubhk.png",
                category: "fruits-vegetables",
                unit: "1kg",
                stock: 60,
                isOrganic: true,
                rating: 4.5,
                reviewCount: 120,
            },
            {
                name: "Fresh Onion 1kg",
                description: "Medium-sized unpeeled onions",
                price: 35,
                originalPrice: 45,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/wnvtwlm2tphqburhsmyc.png",
                category: "fruits-vegetables",
                unit: "1kg",
                stock: 150,
                isOrganic: false,
                rating: 4.6,
                reviewCount: 135,
            },
            {
                name: "Fresh Potato 1kg",
                description: "High-quality, farm-fresh potatoes",
                price: 30,
                originalPrice: 40,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/tzibj2ntsnbn4e0u5kwv.png",
                category: "fruits-vegetables",
                unit: "1kg",
                stock: 200,
                isOrganic: true,
                rating: 4.7,
                reviewCount: 200,
            },
            {
                name: "Kissan Mixed Fruit Jam 500g",
                description: "100% real fruit ingredients",
                price: 160,
                originalPrice: 175,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/zvoeqbvrbrt7atqj0dbu.png",
                category: "pantry-staples",
                unit: "500g",
                stock: 110,
                isOrganic: false,
                rating: 4.8,
                reviewCount: 290,
            },
            {
                name: "Surf Excel Easy Wash 1kg",
                description: "Detergent powder for tough stains",
                price: 135,
                originalPrice: 150,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/dboutcrkdjhoxcvbbqne.png",
                category: "household",
                unit: "1kg",
                stock: 250,
                isOrganic: false,
                rating: 4.8,
                reviewCount: 630,
            },
            {
                name: "Dettol Original Soap 125g x 4",
                description: "Germ protection bathing bar",
                price: 175,
                originalPrice: 195,
                image: "https://raw.githubusercontent.com/avinashdm/gs-images/main/greencart/vy1xa7zovcu22smzapzv.png",
                category: "personal-care",
                unit: "500g",
                stock: 0,
                isOrganic: false,
                rating: 4.9,
                reviewCount: 420,
            }
        ];

        console.log("Adding new products...");
        await Product.insertMany(products);
        console.log("Seed data injected successfully.");
    } catch (error) {
        console.error("Error seeding data:", error);
    } finally {
        await mongoose.disconnect();
        console.log("Disconnected from MongoDB.");
    }
};

seedDB();
